# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_of_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('July', 'July')], max_length=200, null=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2020)])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.CharField(max_length=200, null=True)),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('credi_hour', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct1_marks', models.IntegerField(default=0)),
                ('ct2_marks', models.IntegerField(default=0)),
                ('ct3_marks', models.IntegerField(default=0)),
                ('ct4_marks', models.IntegerField(default=0)),
                ('ct5_marks', models.IntegerField(default=0)),
                ('ct6_marks', models.IntegerField(default=0)),
                ('assignment1_marks', models.IntegerField(default=0)),
                ('assignment2_marks', models.IntegerField(default=0)),
                ('assignment3_marks', models.IntegerField(default=0)),
                ('attendance_marks', models.IntegerField(default=0)),
                ('term_final_marks', models.IntegerField(default=0)),
                ('viva1_marks', models.IntegerField(default=0)),
                ('viva2_marks', models.IntegerField(default=0)),
                ('experiment_marks', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('final_out_of_hundred', models.IntegerField(default=0)),
                ('class_of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Class_of_course')),
            ],
        ),
        migrations.CreateModel(
            name='Option_of_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question_of_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('respodent_type', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response_of_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Option_of_vote')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Question_of_vote')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('phone_num', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.User')),
                ('studentId', models.CharField(max_length=200, unique=True)),
                ('division', models.CharField(blank=True, choices=[('BARISHAL', 'Barishal'), ('CHITTAGONG', 'Chittagong'), ('DHAKA', 'Dhaka'), ('MYMENSINGH', 'Mymensingh'), ('KHULNA', 'Khulna'), ('RAJSHAHI', 'Rajshahi'), ('RANGPUR', 'Rangpur'), ('SYLHET', 'Sylhet')], max_length=200, null=True)),
                ('level', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('term', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('dues', models.IntegerField(default=0)),
            ],
            bases=('cms.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.User')),
                ('joinDate', models.DateField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=200)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Department')),
            ],
            bases=('cms.user',),
        ),
        migrations.AddField(
            model_name='option_of_vote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Question_of_vote'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Department'),
        ),
        migrations.AddField(
            model_name='class_of_course',
            name='course_of_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='classes_enrolled_in',
            field=models.ManyToManyField(through='cms.Enrolment', to='cms.Class_of_course'),
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Department'),
        ),
        migrations.AddField(
            model_name='response_of_vote',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Student'),
        ),
        migrations.AddField(
            model_name='response_of_vote',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Teacher'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Student'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Teacher'),
        ),
        migrations.AddField(
            model_name='class_of_course',
            name='class_teacher',
            field=models.ManyToManyField(to='cms.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='response_of_vote',
            unique_together=set([('question', 'teacher', 'student')]),
        ),
    ]
