# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('studentId', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_nom', models.IntegerField(null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('level', models.IntegerField(null=True)),
                ('term', models.IntegerField(null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Department')),
            ],
        ),
    ]
