# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
