# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170515_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credi_hour',
            new_name='credit_hour',
        ),
    ]
