# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170430_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_enrolled_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Class_of_course')),
                ('student_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together=set([('student_enrolled', 'class_enrolled_in')]),
        ),
    ]
