# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170501_0900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='class_enrolled_in',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='student_enrolled',
        ),
        migrations.AddField(
            model_name='class_of_course',
            name='class_teacher',
            field=models.ManyToManyField(to='cms.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='classes_enrolled_in',
            field=models.ManyToManyField(to='cms.Class_of_course'),
        ),
        migrations.DeleteModel(
            name='enrolment',
        ),
    ]
