# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170515_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='class_of_course',
            unique_together=set([('month', 'year', 'course_of_class')]),
        ),
    ]
