# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170517_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together=set([('student', 'class_of_course')]),
        ),
    ]
