# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_forum_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='forum_post',
            name='headline',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='text',
            field=models.TextField(blank=True, max_length=9999),
        ),
    ]
