# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_forum_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='headline',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='text',
            field=models.TextField(max_length=9999),
        ),
    ]
