# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20170526_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='headline',
            field=models.CharField(max_length=999, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='text',
            field=models.TextField(max_length=9999, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
